name: Android CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest  # 使用 Ubuntu 作为运行环境

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置 JDK 环境
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # 使用 Java 11
          distribution: 'zulu'

      # 缓存 Gradle 依赖
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 下载并设置 Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 31  # Android API 级别
          build-tools: 31.0.0  # 构建工具版本
          ndk: false  # 如果需要 NDK，可以设为 true

      # 构建 APK
      - name: Build APK
        run: ./gradlew assembleRelease  # 根据你的任务修改，例如 assembleDebug

      # 将 APK 保存为构件
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/apprelease.apk